"""PDF generation utilities using WeasyPrint."""

from shared.logger import get_logger
from shared.errors import ProcessingError
import os
import sys
from typing import Any, Dict, Optional

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from weasyprint import CSS, HTML
    from weasyprint.text.fonts import FontConfiguration

    WEASYPRINT_AVAILABLE = True
except ImportError:
    HTML = None
    CSS = None
    FontConfiguration = None
    WEASYPRINT_AVAILABLE = False


logger = get_logger()


def apply_tenant_branding(
    html_content: str, tenant_config: Optional[Dict[str, Any]] = None
) -> str:
    """
    Apply tenant branding (logo, colors) to HTML content.

    Validates: Property 45 - Tenant Branding Application

    Args:
        html_content: Original HTML content
        tenant_config: Tenant configuration with branding settings
            {
                'logo_url': 'https://...',
                'primary_color': '#667eea',
                'secondary_color': '#764ba2',
                'company_name': 'Acme Corp'
            }

    Returns:
        HTML content with tenant branding applied
    """
    if not tenant_config:
        logger.info("No tenant branding configuration provided, using defaults")
        return html_content

    try:
        # Extract branding settings
        logo_url = tenant_config.get("logo_url", "")
        primary_color = tenant_config.get("primary_color", "#667eea")
        secondary_color = tenant_config.get("secondary_color", "#764ba2")
        company_name = tenant_config.get("company_name", "")

        # Replace default gradient with tenant colors
        html_content = html_content.replace(
            "background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);",
            f"background: linear-gradient(135deg, {primary_color} 0%, {secondary_color} 100%);",
        )

        # Replace primary color references
        html_content = html_content.replace(
            "color: #667eea;", f"color: {primary_color};"
        )
        html_content = html_content.replace(
            "border-bottom: 3px solid #667eea;",
            f"border-bottom: 3px solid {primary_color};",
        )
        html_content = html_content.replace(
            "background: #667eea;", f"background: {primary_color};"
        )

        # Add logo if provided
        if logo_url:
            logo_html = f"""
    <div style="text-align: center; margin-bottom: 20px;">
        <img src="{logo_url}" alt="{company_name} Logo" style="max-width: 200px; max-height: 80px;">
    </div>
"""
            # Insert logo after opening body tag
            html_content = html_content.replace("<body>", f"<body>{logo_html}")

        # Add company name to footer if provided
        if company_name:
            html_content = html_content.replace(
                "This report was automatically generated by the AI SW Program Manager platform.",
                f"This report was automatically generated by the AI SW Program Manager platform for {company_name}.",
            )

        logger.info(
            "Tenant branding applied successfully",
            extra={"has_logo": bool(logo_url), "has_company_name": bool(company_name)},
        )

        return html_content

    except Exception as e:
        logger.error(f"Failed to apply tenant branding: {str(e)}")
        # Return original content if branding fails
        return html_content


def convert_html_to_pdf(
    html_content: str, tenant_config: Optional[Dict[str, Any]] = None
) -> bytes:
    """
    Convert HTML content to PDF format using WeasyPrint.

    Validates: Property 44 - PDF Format Conversion

    Args:
        html_content: HTML content to convert
        tenant_config: Optional tenant branding configuration

    Returns:
        PDF content as bytes

    Raises:
        ProcessingError: If PDF generation fails
    """
    if not WEASYPRINT_AVAILABLE:
        raise ProcessingError(
            "WeasyPrint is not available. Install with: pip install weasyprint",
            processing_type="PDF_Generation",
        )

    try:
        logger.info("Starting PDF conversion")

        # Apply tenant branding
        branded_html = apply_tenant_branding(html_content, tenant_config)

        # Configure fonts
        font_config = FontConfiguration()

        # Additional CSS for PDF optimization
        pdf_css = CSS(
            string="""
            @page {
                size: A4;
                margin: 2cm;
            }
            body {
                background-color: white !important;
            }
            .section {
                page-break-inside: avoid;
            }
            .chart img {
                max-width: 100%;
                page-break-inside: avoid;
            }
            table {
                page-break-inside: avoid;
            }
        """,
            font_config=font_config,
        )

        # Convert HTML to PDF
        html_doc = HTML(string=branded_html)
        pdf_bytes = html_doc.write_pdf(stylesheets=[pdf_css], font_config=font_config)

        logger.info(
            "PDF conversion completed successfully",
            extra={"pdf_size_bytes": len(pdf_bytes)},
        )

        return pdf_bytes

    except Exception as e:
        logger.error(f"Failed to convert HTML to PDF: {str(e)}")
        raise ProcessingError(
            f"Failed to convert HTML to PDF: {str(e)}", processing_type="PDF_Generation"
        )


def validate_pdf_generation(pdf_bytes: bytes) -> bool:
    """
    Validate that PDF was generated successfully.

    Args:
        pdf_bytes: PDF content as bytes

    Returns:
        True if valid PDF, False otherwise
    """
    try:
        # Check if bytes start with PDF magic number
        if not pdf_bytes or len(pdf_bytes) < 4:
            return False

        # PDF files start with %PDF-
        pdf_header = pdf_bytes[:4]
        if pdf_header != b"%PDF":
            return False

        # Check minimum size (empty PDF is ~1KB)
        if len(pdf_bytes) < 1000:
            logger.warning("PDF size is suspiciously small")
            return False

        logger.info("PDF validation passed")
        return True

    except Exception as e:
        logger.error(f"PDF validation failed: {str(e)}")
        return False
