"""Application constants."""

# User roles
ROLE_ADMIN = "ADMIN"
ROLE_PROGRAM_MANAGER = "PROGRAM_MANAGER"
ROLE_EXECUTIVE = "EXECUTIVE"
ROLE_TEAM_MEMBER = "TEAM_MEMBER"

VALID_ROLES = [
    ROLE_ADMIN,
    ROLE_PROGRAM_MANAGER,
    ROLE_EXECUTIVE,
    ROLE_TEAM_MEMBER
]

# RAG status
RAG_STATUS_GREEN = "GREEN"
RAG_STATUS_AMBER = "AMBER"
RAG_STATUS_RED = "RED"

VALID_RAG_STATUSES = [
    RAG_STATUS_GREEN,
    RAG_STATUS_AMBER,
    RAG_STATUS_RED
]

# Risk severity levels
RISK_SEVERITY_LOW = "LOW"
RISK_SEVERITY_MEDIUM = "MEDIUM"
RISK_SEVERITY_HIGH = "HIGH"
RISK_SEVERITY_CRITICAL = "CRITICAL"

VALID_RISK_SEVERITIES = [
    RISK_SEVERITY_LOW,
    RISK_SEVERITY_MEDIUM,
    RISK_SEVERITY_HIGH,
    RISK_SEVERITY_CRITICAL
]

# Risk types
RISK_TYPE_VELOCITY_DECLINE = "VELOCITY_DECLINE"
RISK_TYPE_BACKLOG_GROWTH = "BACKLOG_GROWTH"
RISK_TYPE_MILESTONE_SLIPPAGE = "MILESTONE_SLIPPAGE"

VALID_RISK_TYPES = [
    RISK_TYPE_VELOCITY_DECLINE,
    RISK_TYPE_BACKLOG_GROWTH,
    RISK_TYPE_MILESTONE_SLIPPAGE
]

# Document types
DOCUMENT_TYPE_SOW = "SOW"
DOCUMENT_TYPE_BRD = "BRD"
DOCUMENT_TYPE_TECHNICAL_SPEC = "TECHNICAL_SPEC"
DOCUMENT_TYPE_CHANGE_REQUEST = "CHANGE_REQUEST"
DOCUMENT_TYPE_MEETING_MINUTES = "MEETING_MINUTES"
DOCUMENT_TYPE_EXECUTIVE_COMM = "EXECUTIVE_COMM"

VALID_DOCUMENT_TYPES = [
    DOCUMENT_TYPE_SOW,
    DOCUMENT_TYPE_BRD,
    DOCUMENT_TYPE_TECHNICAL_SPEC,
    DOCUMENT_TYPE_CHANGE_REQUEST,
    DOCUMENT_TYPE_MEETING_MINUTES,
    DOCUMENT_TYPE_EXECUTIVE_COMM
]

# Allowed file formats
ALLOWED_FILE_FORMATS = [".pdf", ".docx", ".txt"]

# File size limits
MAX_FILE_SIZE_MB = 50
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

# Integration types
INTEGRATION_TYPE_JIRA = "JIRA"
INTEGRATION_TYPE_AZURE_DEVOPS = "AZURE_DEVOPS"

VALID_INTEGRATION_TYPES = [
    INTEGRATION_TYPE_JIRA,
    INTEGRATION_TYPE_AZURE_DEVOPS
]

# Report types
REPORT_TYPE_WEEKLY_STATUS = "WEEKLY_STATUS"
REPORT_TYPE_EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"

VALID_REPORT_TYPES = [
    REPORT_TYPE_WEEKLY_STATUS,
    REPORT_TYPE_EXECUTIVE_SUMMARY
]

# Prediction types
PREDICTION_TYPE_DELAY = "DELAY"
PREDICTION_TYPE_WORKLOAD = "WORKLOAD"

VALID_PREDICTION_TYPES = [
    PREDICTION_TYPE_DELAY,
    PREDICTION_TYPE_WORKLOAD
]

# Milestone status
MILESTONE_STATUS_ON_TRACK = "ON_TRACK"
MILESTONE_STATUS_AT_RISK = "AT_RISK"
MILESTONE_STATUS_DELAYED = "DELAYED"
MILESTONE_STATUS_COMPLETED = "COMPLETED"

VALID_MILESTONE_STATUSES = [
    MILESTONE_STATUS_ON_TRACK,
    MILESTONE_STATUS_AT_RISK,
    MILESTONE_STATUS_DELAYED,
    MILESTONE_STATUS_COMPLETED
]

# Health score weights (default)
DEFAULT_HEALTH_SCORE_WEIGHTS = {
    "velocity": 0.30,
    "backlog": 0.25,
    "milestones": 0.30,
    "risks": 0.15
}

# RAG status thresholds (default)
DEFAULT_RAG_THRESHOLDS = {
    "green": 80,
    "amber": 60
}

# API rate limiting
DEFAULT_RETRY_DELAYS = [1, 2, 4, 8, 16]  # Exponential backoff in seconds
MAX_RETRY_ATTEMPTS = 5
MAX_RETRY_DELAY = 60  # Maximum delay in seconds

# Cache TTLs
CACHE_TTL_DASHBOARD = 300  # 5 minutes
CACHE_TTL_REPORTS = 3600  # 1 hour

# Token expiration
ACCESS_TOKEN_EXPIRY_SECONDS = 3600  # 1 hour
REFRESH_TOKEN_EXPIRY_SECONDS = 2592000  # 30 days

# PDF download link expiration
PDF_DOWNLOAD_LINK_EXPIRY_SECONDS = 86400  # 24 hours

# Executive summary constraints
EXECUTIVE_SUMMARY_MAX_WORDS = 500
EXECUTIVE_SUMMARY_MAX_PAGES = 1

# Search result limits
DEFAULT_SEARCH_LIMIT = 10
MAX_SEARCH_LIMIT = 100

# Embedding dimensions
BEDROCK_TITAN_EMBEDDING_DIMENSION = 1536

# Confidence thresholds
LOW_CONFIDENCE_THRESHOLD = 0.7
EXTRACTION_ACCURACY_TARGET = 0.85

# Delay probability threshold for alerting
DELAY_PROBABILITY_ALERT_THRESHOLD = 60  # percentage

# Velocity decline thresholds
VELOCITY_DECLINE_THRESHOLD = 0.20  # 20%
VELOCITY_DECLINE_CONSECUTIVE_SPRINTS = 2

# Backlog growth thresholds
BACKLOG_GROWTH_WEEKLY_THRESHOLD = 0.30  # 30%
BACKLOG_SIZE_COMPLETION_RATE_MULTIPLIER = 2

# Milestone slippage thresholds
MILESTONE_COMPLETION_THRESHOLD = 0.70  # 70%
MILESTONE_TIME_REMAINING_THRESHOLD = 0.20  # 20%

# Workload imbalance threshold
WORKLOAD_VARIANCE_THRESHOLD = 0.40  # 40%

# Model retraining
MODEL_ACCURACY_IMPROVEMENT_THRESHOLD = 0.05  # 5%

# Log retention
CLOUDWATCH_LOG_RETENTION_DAYS = 90
AUDIT_LOG_RETENTION_DAYS = 365

# Email retry
EMAIL_MAX_RETRIES = 3
